action_dim: 4
batch_size: 64
beta1: 0.9
config: multimodal/configs/training_default.yaml
contact: 1.0
continuation: false
cuda: true
dataset: multimodal/dataset/triangle_real_data/
dataset_params:
  action_dim: 4
  force_name: force
depth: 1.0
deterministic: false
dev: false
eedelta: 1.0
encoder: false
ep_length: 50
force: 1.0
img_record_n: 500
latest_weights: multimodal/logging/202307212225_/models/weights_itr_49.ckpt
load: ''
log_level: INFO
logging_folder: multimodal/logging/
lr: 0.0001
max_epoch: 50
notes: ''
num_workers: 8
opticalflow: 1.0
pairing: 1.0
proprio: 1.0
sceneflow: 1.0
seed: 1234
test: false
training_type: selfsupervised
val_ratio: 0.2
vision: 1.0
zdepth: 2
zdim: 128
